# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170524_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 5, 24, 21, 43, 38, 421000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
